# run source env-vars.sh so that the following environment variables are usable
# in your current current shell session

export WHYD_GENUINE_SIGNUP_SECRET=""
export WHYD_SESSION_SECRET=""
export WHYD_DEV_APNS_PASSPHRASE=""
export WHYD_APNS_PASSPHRASE=""
export WHYD_ADMIN_OBJECTID=""
export WHYD_ADMIN_NAME=""
export WHYD_ADMIN_EMAIL=""
export WHYD_CONTACT_EMAIL=""
export WHYD_CRASH_EMAIL=""
export WHYD_URL_PREFIX="http://localhost:8080"
export WHYD_PORT="8080"
export WHYD_DEV="true"
export MONGODB_DATABASE="openwhyd_data"
export MONGODB_HOST="localhost"
export MONGODB_PORT="27017"
export MONGODB_USER=""
export MONGODB_PASS=""
export SENDGRID_API_USER=""
export SENDGRID_API_KEY=""
export SENDGRID_API_FROM_EMAIL=""
export SENDGRID_API_FROM_NAME=""
export LAST_FM_API_KEY=""
export LAST_FM_API_SECRET=""
export ALGOLIA_APP_ID=""
export ALGOLIA_API_KEY=""
