module.exports = ({ ObjectId }) => [
  {
    _id: ObjectId('6106450aa1de931f401c43be'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: '👨‍💻 epic coding session soundtrack',
      id: 53,
    },
    name: 'BOYLE - Roppongi Hills (Music Video)',
    eId: '/yt/jI3YrVfOksE',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/jI3YrVfOksE/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=jI3YrVfOksE',
      name: 'BOYLE - Roppongi Hills (Music Video) - YouTube',
    },
    nbP: 3,
    lov: ['4d94501d1f78ac091dbc9b4d'],
  },
  {
    _id: ObjectId('60e82f5ea9727659af9d195e'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '80\'s "city pop" from japan',
    pl: {
      name: '👶 Nostalgia',
      id: 14,
    },
    name: "AB'S - By The End of Century",
    eId: '/yt/E6SAirZ1FD4',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/E6SAirZ1FD4/default.jpg',
    src: {
      id: 'https://music.youtube.com/watch?v=E6SAirZ1FD4&list=PLmzn1C-VN6G7DKpdkWXUGzF_PduNWcdkZ',
      name: 'AB&#39;S - By The End of Century - YouTube Music',
    },
    nbP: 2,
    lov: [],
  },
  {
    _id: ObjectId('60e82e2ea9727659af9d195d'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'japanese funk / city pop',
    pl: {
      name: '🕶 soul / funk / jazz / etc...',
      id: 11,
    },
    name: 'TOSHIKI KADOMATSU - If You (Wanna Dance Tonight). (1984)',
    eId: '/yt/faondb5n3qA',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/faondb5n3qA/default.jpg',
    src: {
      id: 'https://music.youtube.com/watch?v=faondb5n3qA&list=PLmzn1C-VN6G7DKpdkWXUGzF_PduNWcdkZ',
      name: 'TOSHIKI KADOMATSU - If You (Wanna Dance Tonight). (1984) - YouTube Music',
    },
    nbP: 2,
    lov: [],
  },
  {
    _id: ObjectId('60e5a93aa9727659af9d186f'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'groovy city pop (japan)',
    pl: {
      name: '🍹 The lounge',
      id: 41,
    },
    name: 'Taeko Onuki  - 4:00 A.M.',
    eId: '/yt/ejvUU6mxiFw',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/ejvUU6mxiFw/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=ejvUU6mxiFw',
      name: '4:00 A.M. - YouTube',
    },
    nbP: 2,
    lov: ['53f4ee46e04b7b4fca7dcea3'],
  },
  {
    _id: ObjectId('60e2bd44dfb5463641b99d8a'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'great city pop track (japan), live',
    pl: {
      name: '🎟  aLIVE',
      id: 39,
    },
    name: 'Mariya Takeuchi — Plastic Love (Vocals by Tatsuro Yamashita) Live Audio',
    eId: '/yt/uuuHggGS5H0',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/uuuHggGS5H0/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=uuuHggGS5H0',
      name: 'Mariya Takeuchi — Plastic Love (Vocals by Tatsuro Yamashita) Live Audio - YouTube',
    },
    nbP: 2,
    lov: [],
  },
  {
    _id: ObjectId('60d1b1dbc421043f40f9f0c9'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'cool afro-beat cover',
    pl: {
      name: '🍻 Apéro !',
      id: 52,
    },
    name: 'Everybody Wants to Rule the World | Tears for Fears | funk cover ft. Cory Henry',
    eId: '/yt/kPDT4SM_WSg',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/kPDT4SM_WSg/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=kPDT4SM_WSg',
      name: 'Everybody Wants to Rule the World | Tears for Fears | funk cover ft. Cory Henry - YouTube',
    },
    nbP: 3,
    lov: [],
  },
  {
    _id: ObjectId('60bdd123c421043f40f9eb59'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'Vulfpeck',
    pl: {
      name: '🎟  aLIVE',
      id: 39,
    },
    name: 'THE FEARLESS FLYERS /// Introducing the Fearless Flyers (Live at Madison Square Garden)',
    eId: '/yt/s_voatSul9Y',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/s_voatSul9Y/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=s_voatSul9Y',
      name: 'THE FEARLESS FLYERS /// Introducing the Fearless Flyers (Live at Madison Square Garden) - YouTube',
    },
    nbP: 5,
    lov: [],
  },
  {
    _id: ObjectId('60af54a150a71e51519b0def'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'excellent modern country from Tennessee, live, for tiny desk (home) concerts',
    pl: {
      name: '🍺 Bar tunes',
      id: 19,
    },
    name: 'Brothers Osborne: Tiny Desk (Home) Concert',
    eId: '/yt/YN3SNoTrLY4',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/YN3SNoTrLY4/default.jpg',
    nbP: 7,
    lov: [],
  },
  {
    _id: ObjectId('60adf05f50a71e51519b0ce9'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: '🎟  aLIVE',
      id: 39,
    },
    name: 'Deep Sea Diver: Tiny Desk (Home) Concert',
    eId: '/yt/0pq_xv1PB28',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/0pq_xv1PB28/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=0pq_xv1PB28',
      name: 'Deep Sea Diver: Tiny Desk (Home) Concert - YouTube',
    },
    nbP: 4,
    lov: [],
  },
  {
    _id: ObjectId('609a421faa2a60553556fa87'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: "🌄 Today's the day",
      id: 31,
    },
    name: 'Doves - There Goes The Fear',
    eId: '/yt/SneuvKIkM3A',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/SneuvKIkM3A/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=SneuvKIkM3A',
      name: 'Doves - There Goes The Fear - YouTube',
    },
    lov: [],
  },
  {
    _id: ObjectId('6082b2d1df1f6639469d5ff1'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'Songs:\nHold Yourself\nHypnotized\nMy Neighbor\nMake It Right',
    pl: {
      name: '🎟  aLIVE',
      id: 39,
    },
    name: 'Tune Yards - Full Performance (Live on KEXP at Home)',
    eId: '/yt/laGUZH0YOkg',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/laGUZH0YOkg/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=laGUZH0YOkg',
      name: 'Tune Yards - Full Performance (Live on KEXP at Home) - YouTube',
    },
    nbP: 11,
    lov: [],
  },
  {
    _id: ObjectId('605de34a8527b12c4d68acc8'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: '🎼  Classical & epic',
      id: 1,
    },
    name: 'Seong-Jin Cho – Debussy: Suite bergamasque, L.75: III. Clair de lune',
    eId: '/yt/U3u4pQ4WKOk',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/U3u4pQ4WKOk/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=U3u4pQ4WKOk&list=WL&index=17',
      name: 'Seong-Jin Cho – Debussy: Suite bergamasque, L.75: III. Clair de lune - YouTube',
    },
    nbP: 11,
    lov: [],
  },
  {
    _id: ObjectId('603b8d45e340af5ea930d177'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'an amazing gospel-like energy!',
    name: 'Kirk Franklin: Tiny Desk (Home) Concert',
    eId: '/yt/wRwId2RfmfA',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/wRwId2RfmfA/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=wRwId2RfmfA&list=WL&index=12',
      name: 'Kirk Franklin: Tiny Desk (Home) Concert - YouTube',
    },
    pl: {
      name: '🎉 Celebration!',
      id: 33,
    },
    nbP: 5,
    lov: [],
  },
  {
    _id: ObjectId('603b8ce1e340af5ea930d176'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: '🎟  aLIVE',
      id: 39,
    },
    name: 'Sampa The Great: Tiny Desk (Home) Concerts',
    eId: '/yt/svxhRbzGpMU',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/svxhRbzGpMU/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=svxhRbzGpMU&list=WL&index=12',
      name: 'Sampa The Great: Tiny Desk (Home) Concerts - YouTube',
    },
    nbP: 2,
    lov: [],
  },
  {
    _id: ObjectId('6034db76e340af5ea930cd8b'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: '👶 Nostalgia',
      id: 14,
    },
    name: 'Imagination - Just An Illusion (Official Video)',
    eId: '/yt/uY4cVhXxW64',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/uY4cVhXxW64/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=uY4cVhXxW64',
      name: 'Imagination - Just An Illusion (Official Video) - YouTube',
    },
    nbP: 7,
    nbR: 3,
    lov: ['53f4ee46e04b7b4fca7dcea3', '603b8ba908ced3543df3a7c7'],
  },
  {
    _id: ObjectId('6033b231e340af5ea930ccfe'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'découvert sur radio fip',
    pl: {
      name: '🍹 The lounge',
      id: 41,
    },
    name: 'Noname - Window (Feat. Phoelix)',
    eId: '/yt/LVah-Ep_sCM',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/LVah-Ep_sCM/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=LVah-Ep_sCM',
      name: 'Window - YouTube',
    },
    nbP: 6,
    lov: [],
  },
  {
    _id: ObjectId('602a398e764e2f52c8f4ffe9'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: "🌄 Today's the day",
      id: 31,
    },
    name: 'Modern Baseball - "Wedding Singer" (Official Music Video)',
    eId: '/yt/MJXGscQdKyQ',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/MJXGscQdKyQ/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=MJXGscQdKyQ',
      name: 'Modern Baseball - &quot;Wedding Singer&quot; (Official Music Video) - YouTube',
    },
    nbP: 4,
    lov: [],
  },
  {
    _id: ObjectId('602a3705764e2f52c8f4ffe8'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'sounds like the OST of an anime, I love it!',
    pl: {
      name: '👟 Indie rock / Shoegaze',
      id: 34,
    },
    name: 'Crying - "Wool in the Wash" (Official Audio)',
    eId: '/yt/kryuiydSOCI',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/kryuiydSOCI/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=kryuiydSOCI',
      name: 'Crying - &quot;Wool in the Wash&quot; (Official Audio) - YouTube',
    },
    nbP: 4,
    nbR: 1,
    lov: [],
  },
  {
    _id: ObjectId('601d160ea7db502dd31d204e'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: 'weird r&b discovered thanks to tiny desk (home) concerts',
    pl: {
      name: '💀 Hangover',
      id: 58,
    },
    name: 'Gabriel Garzón-Montano - Tombs (Official Audio) // Agüita LP',
    eId: '/yt/D2eqc3fJpDg',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/D2eqc3fJpDg/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=D2eqc3fJpDg',
      name: '(1) Gabriel Garzón-Montano - Tombs (Official Audio) // Agüita LP - YouTube',
    },
    nbP: 5,
    lov: [],
  },
  {
    _id: ObjectId('600ec1c703e2014e630c8137'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: '🍔 Covers + fun',
      id: 6,
    },
    name: 'Konnakkol Duet (INSANE RHYTHMS) Metal Version || Artificial Fear',
    eId: '/yt/ZAVZtCZV9aI',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/ZAVZtCZV9aI/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=ZAVZtCZV9aI&feature=youtu.be',
      name: 'Konnakkol Duet (INSANE RHYTHMS) Metal Version || Artificial Fear - YouTube',
    },
    nbP: 2,
    lov: [],
  },
  {
    _id: ObjectId('600e7fda03e2014e630c811b'),
    uId: '4d94501d1f78ac091dbc9b4d',
    uNm: 'Adrien Joly',
    text: '',
    pl: {
      name: '🎈 Music in wonderland',
      id: 18,
    },
    name: 'Typhoon - Empire Builder',
    eId: '/yt/jlTJeIeWXgk',
    ctx: 'bk',
    img: 'https://i.ytimg.com/vi/jlTJeIeWXgk/default.jpg',
    src: {
      id: 'https://www.youtube.com/watch?v=jlTJeIeWXgk',
      name: 'Empire Builder - YouTube',
    },
    lov: ['518b5a447e91c862b2adea1a'],
    nbP: 3,
    nbR: 1,
  },
  {
    _id: ObjectId('60eca407a9727659af9d1a9c'),
    uId: '000000000000000000000001',
    uNm: 'Admin',
    text: '',
    pl: { name: 'Punk', id: 13 },
    name: "Fishbone - Skankin' To The Beat",
    eId: '/yt/CywetPs8MZE',
    img: 'https://i.ytimg.com/vi/CywetPs8MZE/0.jpg',
    repost: {
      pId: '5568dede0f253b6519ffa8e5',
      uId: '548332e0e04b7b4fca818ec3',
      uNm: 'MAUREL',
    },
    lov: [],
    nbR: 0,
    nbP: 0,
  },
];
