engines: 
  eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: whydJS/.eslintrc
  duplication:
    enabled: true
    config:
      languages:
      - javascript

ratings:
  paths:
    - "whydJS/app/**.js"
