engines: 
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  # eslint:
  #   enabled: true
  #   channel: "eslint-2"
  #   config:
  #     config: whydJS/.eslintrc

ratings:
  paths:
    - "whydJS/app/**.js"
