engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: 'eslint-2'
    config:
      config: ./.eslintrc

ratings:
  paths:
    - './app/**.js'

exclude_patterns:
  - './config/'
  - './public/js/jquery*.js'
  - './public/js/soundmanager2.js'
  - './public/js/*-all.js'
  - './public/js/*-min.js'
  - './public/js/*.min.js'
  - 'features/'
  - '**/node_modules/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - '**/vendor/'
  - '**/*.d.ts'
