version: '3'
services:
  mongo:
    image: mongo:4.4.29@sha256:52c42cbab240b3c5b1748582cc13ef46d521ddacae002bbbda645cebed270ec0
    command: mongod --port 27017
    volumes:
      - target: /data
        type: tmpfs
    ports:
      - '27117:27017'
    restart: 'always'

  web:
    restart: 'always'
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    env_file:
      - 'env-vars-testing.conf'
    environment:
      - DISABLE_DATADOG=true
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - ALGOLIA_APP_ID
      - ALGOLIA_API_KEY
