version: '3'
services:
  mongo:
    image: mongo:3.4
    command: mongod --port 27117
    volumes:
      - /data # Data Persistance

  web:
    image: openwhyd/openwhyd
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - mongo
    env_file:
      - 'env-vars-testing.conf'
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27117
