#!/bin/bash

# This script generate files that analyse and report the structure and complexity of the source code.
# Usage: $ scripts/code-analysis/report.sh

THIS_DIR=$(dirname "$0")

npx --yes code-complexity@v4.2.2 . \
  --filter 'app/**/*.js' \
  --sort name \
  --format \
  | perl -pe 's/\x1b\[[0-9;]*[mG]//g' \
  > ${THIS_DIR}/code-complexity.txt

npx --yes arkit app/ -o ${THIS_DIR}/arkit.svg

npx --yes dependency-cruiser app --config --exclude node_modules --output-type ddot | dot -T svg -Grankdir=TD > ${THIS_DIR}/dependency-ddot.svg      

npx --yes dependency-cruiser app --config --exclude node_modules --output-type archi | dot -T svg -Grankdir=TD > ${THIS_DIR}/dependency-archi.svg

cat > ${THIS_DIR}/dependency-graph.md << CONTENT
# Dependency analysis generated by \`${THIS_DIR}/report.sh\`

$(npx dependency-cruiser app --config --exclude node_modules --output-type markdown)

## DDot graph

![](./${THIS_DIR}/dependency-ddot.svg)

## Archi graph

![](./${THIS_DIR}/dependency-archi.svg)

## Full dependency graph

\`\`\`mermaid
$(npx --yes dependency-cruiser app --config --exclude node_modules --output-type mermaid)
\`\`\`
CONTENT
