#!/bin/sh

OUTPUT_FILE="public/js/bookmarklet.js"

npx --yes --package typescript tsc --target ES2015 --module none --moduleResolution node --outFile "${OUTPUT_FILE}" public/js/bookmarklet*.ts
TRANSPILED_CODE=$(cat "${OUTPUT_FILE}")

cat >"${OUTPUT_FILE}" << CONTENT
/***********************************************/
/* Automatically generated from bookmarklet.ts */
/*       DO NOT EDIT THIS FILE MANUALLY        */
/***********************************************/
(() => {${TRANSPILED_CODE}})();
CONTENT

npx --yes prettier "${OUTPUT_FILE}" --write
