#!/bin/sh

OUTPUT_FILE="public/js/bookmarklet.js"

# Make sure that public/js/bookmarkletUI.ts is transpiled last, because it relies on variables from other files
npx --yes --package typescript tsc --target ES2015 --module none --moduleResolution node --outFile "${OUTPUT_FILE}" public/js/bookmarkletUrlDetectors.ts public/js/bookmarkletPageDetectors.ts public/js/bookmarkletYouTube.ts public/js/bookmarkletLogic.ts public/js/bookmarkletUI.ts
TRANSPILED_CODE=$(cat "${OUTPUT_FILE}")

cat >"${OUTPUT_FILE}" << CONTENT
/***********************************************/
/* Automatically generated from bookmarklet.ts */
/*       DO NOT EDIT THIS FILE MANUALLY        */
/***********************************************/
(() => {${TRANSPILED_CODE}})();
CONTENT

npx --yes prettier "${OUTPUT_FILE}" --write
