#!/bin/sh

OUTPUT_FILE="public/js/bookmarklet.js"

npx tsc --module none --outFile "${OUTPUT_FILE}" public/js/bookmarklet*.ts
TRANSPILED_CODE=$(cat "${OUTPUT_FILE}")

cat >"${OUTPUT_FILE}" << CONTENT
/***********************************************/
/* Automatically generated from bookmarklet.ts */
/*       DO NOT EDIT THIS FILE MANUALLY        */
/***********************************************/
${TRANSPILED_CODE}
CONTENT

npx prettier "${OUTPUT_FILE}" --write
