# for Jekyll, static md to html file generation of docs/
# see https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/#step-2-install-jekyll-using-bundler
source 'https://rubygems.org'
gem 'github-pages', group: :jekyll_plugins
