name: Docker

on:
  # Run tests on Pull Requests that target master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and start services
        run: |
          docker-compose up --build --detach

      - name: Init database for tests
        run: |
          docker-compose exec -T web npm run test-reset
          docker-compose restart web
          docker-compose exec -T web sh -c './scripts/wait-for-http-server.sh 8080'

      - name: Run unit tests
        run: |
          docker-compose exec -T web npm run test-unit

      - name: Run API tests
        run: |
          docker-compose exec -T web npm run test-api

      - name: Run Cypress E2E tests
        run: |
          apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb # cf https://docs.cypress.io/guides/guides/continuous-integration.html#Linux
          docker-compose exec -T web npm install # also install dev dependencies (including cypress and typescript)
          docker-compose exec -T web npm run test:cypress

# To publish the Docker image from here, see https://github.com/openwhyd/openwhyd/pull/308/commits/1eacaa98885789642ba0073c9bb4d822021f0d95#diff-12a86cef0c4707531fdbabac3e38cb2aR36
